from pathlib import Path
from typing import Literal

from langchain.messages import ToolMessage
from langchain.tools import tool, ToolRuntime
import os
from core.config import settings
from langchain_protocol import Command
from ollama import chat
from langchain.agents.middleware import (
    FilesystemFileSearchMiddleware,
)

import subprocess
import sys


# @tool("execute_python_task")
# def execute_python_task(
#     script: str,
#     toolRunTime: ToolRuntime,
# ) -> str:
#     """
#     Execute a Python script on the user's Windows computer.

#     The script is generated by the agent. Use this for filesystem
#     and local computer tasks.
#     """

#     writer = toolRunTime.stream_writer

#     writer({"message": "Executing Python script..."})

#     print("\n========== SCRIPT ==========")
#     print(script)
#     print("============================\n")

#     try:
#         result = subprocess.run(
#             [sys.executable, "-c", script],
#             capture_output=True,
#             text=True,
#             timeout=20,
#             shell=False,
#         )

#         if result.returncode != 0:
#             writer({"message": "Script execution failed."})

#             return f"Script failed:\n{result.stderr}"

#         writer({"message": "Script completed."})

#         return result.stdout.strip() or "Script completed successfully."

#     except subprocess.TimeoutExpired:
#         writer({"message": "Script timed out."})

#         return "Script execution timed out."

#     except Exception as e:
#         writer({"message": ""})

#         return f"Error executing script: {e}"


@tool("read_image")
def read_image(
    task: str,
    path: str,
    tool_runtime: ToolRuntime,
) -> str:
    """
    Read and analyze an image file from the user's computer.
    Use this when the user asks what is inside an image.
    """

    writer = tool_runtime.stream_writer

    image_path = Path(path)

    if not image_path.exists():
        return f"Image not found: {image_path}"

    if not image_path.is_file():
        return f"Path is not a file: {image_path}"

    try:
        img = image_path.read_bytes()

        writer({"message": f"Reading image: {image_path.name}"})

        response = chat(
            model="gemma4:e2b",
            messages=[
                {
                    "role": "user",
                    "content": task,
                    "images": [img],
                }
            ],
        )

        return response.message.content

    except Exception as e:
        return f"Failed to read image: {e}"


from tavily import TavilyClient

tavily_client = TavilyClient(api_key=settings.TAVILY_API_KEY)


def internet_search(
    query: str,
    max_results: int = 5,
    topic: Literal["general", "news", "finance"] = "general",
    include_raw_content: bool = False,
):
    """Run a web search"""
    return tavily_client.search(
        query,
        max_results=max_results,
        include_raw_content=include_raw_content,
        topic=topic,
    )


@tool
def extract_directory(path: str) -> str:
    """Extract the directory path provided by the user from the conversation.

    path: extract path from conversation
    """
    request.app.state.root_path = r"C:\Users\Rashm\OneDrive\Desktop\path2"

    # Execute search logic against the specified directory path
    return f"Searched {directory_path} for {query}"
